name: cuda

on:
  push:
    branches: [ "testnet3-direct-cuda" ]
  pull_request:
    branches: [ "testnet3-direct-cuda" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: cuda-toolkit
      uses: Jimver/cuda-toolkit@v0.2.8
      with:
        # Cuda version
        cuda: 11.8.0 # optional, default is 11.7.0
    - name: Build
      run: cargo build --release --features cuda